"""create current runtime tables

Revision ID: aec69eff0019
Revises:
Create Date: 2026-06-01 15:57:14.293441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec69eff0019'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=80), nullable=True),
    sa.Column('default_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers'))
    )
    op.create_index('ix_customers_tenant_id_phone', 'customers', ['tenant_id', 'customer_phone'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.String(length=80), nullable=True),
    sa.Column('customer_name_snapshot', sa.String(length=120), nullable=True),
    sa.Column('customer_phone_snapshot', sa.String(length=80), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('packaging_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fulfillment_type', sa.String(length=40), nullable=True),
    sa.Column('delivery_zone', sa.String(length=120), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('delivery_date', sa.String(length=120), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmation_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders'))
    )
    op.create_index('ix_orders_tenant_id_created_at', 'orders', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_orders_tenant_id_customer_id', 'orders', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_orders_tenant_id_status', 'orders', ['tenant_id', 'status'], unique=False)
    op.create_table('parse_log',
    sa.Column('parse_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=120), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('parse_id', name=op.f('pk_parse_log'))
    )
    op.create_index('ix_parse_log_tenant_id_created_at', 'parse_log', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_parse_log_tenant_id_success', 'parse_log', ['tenant_id', 'success'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('available_days', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products'))
    )
    op.create_index('ix_products_tenant_id_active', 'products', ['tenant_id', 'active'], unique=False)
    op.create_index('ix_products_tenant_id_category', 'products', ['tenant_id', 'category'], unique=False)
    op.create_table('stock_movements',
    sa.Column('stock_movement_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('stock_movement_id', name=op.f('pk_stock_movements'))
    )
    op.create_index('ix_stock_movements_tenant_id_created_at', 'stock_movements', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_stock_movements_tenant_id_product_id', 'stock_movements', ['tenant_id', 'product_id'], unique=False)
    op.create_index('ix_stock_movements_tenant_id_reference_id', 'stock_movements', ['tenant_id', 'reference_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('order_id', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.String(length=80), nullable=True),
    sa.Column('product_name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('modifications', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_order_items_tenant_id_order_id', 'order_items', ['tenant_id', 'order_id'], unique=False)
    op.create_index('ix_order_items_tenant_id_product_id', 'order_items', ['tenant_id', 'product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_tenant_id_product_id', table_name='order_items')
    op.drop_index('ix_order_items_tenant_id_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_stock_movements_tenant_id_reference_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_tenant_id_product_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_tenant_id_created_at', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_products_tenant_id_category', table_name='products')
    op.drop_index('ix_products_tenant_id_active', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_parse_log_tenant_id_success', table_name='parse_log')
    op.drop_index('ix_parse_log_tenant_id_created_at', table_name='parse_log')
    op.drop_table('parse_log')
    op.drop_index('ix_orders_tenant_id_status', table_name='orders')
    op.drop_index('ix_orders_tenant_id_customer_id', table_name='orders')
    op.drop_index('ix_orders_tenant_id_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_customers_tenant_id_phone', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
